# Generated by Django 4.2.18 on 2025-02-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Boutique', 'Boutique'), ('Bakery', 'Bakery'), ('Flower Shop', 'Flower Shop')], max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='shop_images/')),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
